name: docs

on:
  push:
    branches: [ master, docs ]

jobs:
  tsdoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
  	    with:
          node-version: 18
          
      - name: Build docs with Typedoc
        run: npm run docs
        
      - name: Copy to Documentation Website Location
        run: |
          cp -rf ./docs/. gh-pages

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: gh-pages

