name: test

on:
  pull_request:
    branches-ignore:
      - "main"

jobs:
  tsdoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install modules
        run: npm install

      - name: Add environment files
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      
      - name: Run tests
        run: |
          npm run test